import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import RightPanel from "@/components/shared/RightPanel";
import Footer from "@/components/shared/Footer";

const poppins = Poppins({
  weight: "400",
});

export const metadata: Metadata = {
  title: "КудаПоеду",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-[#EFEFEF] h-full`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
